[package]
name = "c-discord-rich-presence"
version = "0.1.0"
edition = "2018"

[lib]
crate-type=["staticlib","cdylib"]

[dependencies]
log = "0.4.7"
discord-rich-presence = "0.2.3"
simple_logger = "4.0.0"
