[package]
name = "gctex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["cdylib"]

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.57"
cc = "1.0"
