[package]
name = "riistudio_rs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type=["staticlib"]

[dependencies]
unzpack = "0.1"
log = "0.4.7"
simple_logger = "4.0.0"
discord-rich-presence = "0.2.3"
